name: Build J2cl WASM app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      # Read the Bazel version from the .bazelversion file
      - name: Get Bazel version
        id: bazel-version
        run: |
          BAZEL_VERSION=$(cat .bazelversion)
          echo "BAZEL_VERSION=$BAZEL_VERSION" >> $GITHUB_ENV

      # Set up Bazel using bazel-contrib/setup-bazel with caching
      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazel-version: ${{ env.BAZEL_VERSION }}
          # Avoid downloading Bazel every time
          bazelisk-cache: true
          # Store build cache per workflow
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows
          repository-cache: true

      # Build the project
      - name: Build J2cl WASM app
        run: bazel build src/main/java/com/google/j2cl/samples/wasm:jsapp
